package pacmon.view.screen.game;

public enum MazeTiles 
{
	  WALL
	, GROUND
	
	// Border Tiles
	, BORDER_UP_0_WALL
	, BORDER_UP_1_WALL_LEFT
	, BORDER_UP_1_WALL_DOWN
	, BORDER_UP_1_WALL_RIGHT
	, BORDER_UP_2_WALL_LEFT_DOWN
	, BORDER_UP_2_WALL_LEFT_RIGHT
	, BORDER_UP_2_WALL_DOWN_RIGHT
	
	, BORDER_LEFT_0_WALL
	, BORDER_LEFT_1_WALL_UP
	, BORDER_LEFT_1_WALL_DOWN
	, BORDER_LEFT_1_WALL_RIGHT
	, BORDER_LEFT_2_WALL_UP_DOWN
	, BORDER_LEFT_2_WALL_UP_RIGHT
	, BORDER_LEFT_2_WALL_DOWN_RIGHT
	
	, BORDER_DOWN_0_WALL
	, BORDER_DOWN_1_WALL_UP
	, BORDER_DOWN_1_WALL_LEFT
	, BORDER_DOWN_1_WALL_RIGHT
	, BORDER_DOWN_2_WALL_UP_LEFT
	, BORDER_DOWN_2_WALL_UP_RIGHT
	, BORDER_DOWN_2_WALL_LEFT_RIGHT
	
	, BORDER_RIGHT_0_WALL
	, BORDER_RIGHT_1_WALL_UP
	, BORDER_RIGHT_1_WALL_LEFT
	, BORDER_RIGHT_1_WALL_DOWN
	, BORDER_RIGHT_2_WALL_UP_LEFT
	, BORDER_RIGHT_2_WALL_UP_DOWN
	, BORDER_RIGHT_2_WALL_LEFT_DOWN
	
	;
	
}
